# This builds, tests, docs
name: PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version-file: .java-version
        distribution: temurin
        cache: maven
    - run: mvn -B -Prelease package
