# This builds, tests, docs and then publishes to GitHub Packages.
name: Build and publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: temurin
          cache: maven
      - run: mvn -B -Prelease deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}